// Generated by gencpp from file crazyflie_mpc/MotorControl.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_MPC_MESSAGE_MOTORCONTROL_H
#define CRAZYFLIE_MPC_MESSAGE_MOTORCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crazyflie_mpc
{
template <class ContainerAllocator>
struct MotorControl_
{
  typedef MotorControl_<ContainerAllocator> Type;

  MotorControl_()
    : m1(0)
    , m2(0)
    , m3(0)
    , m4(0)  {
    }
  MotorControl_(const ContainerAllocator& _alloc)
    : m1(0)
    , m2(0)
    , m3(0)
    , m4(0)  {
  (void)_alloc;
    }



   typedef uint16_t _m1_type;
  _m1_type m1;

   typedef uint16_t _m2_type;
  _m2_type m2;

   typedef uint16_t _m3_type;
  _m3_type m3;

   typedef uint16_t _m4_type;
  _m4_type m4;





  typedef boost::shared_ptr< ::crazyflie_mpc::MotorControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyflie_mpc::MotorControl_<ContainerAllocator> const> ConstPtr;

}; // struct MotorControl_

typedef ::crazyflie_mpc::MotorControl_<std::allocator<void> > MotorControl;

typedef boost::shared_ptr< ::crazyflie_mpc::MotorControl > MotorControlPtr;
typedef boost::shared_ptr< ::crazyflie_mpc::MotorControl const> MotorControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyflie_mpc::MotorControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyflie_mpc::MotorControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crazyflie_mpc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'crazyflie_mpc': ['/home/joseph/other_research/crazyflie_ros/src/crazyflie_mpc/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie_mpc::MotorControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie_mpc::MotorControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie_mpc::MotorControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie_mpc::MotorControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie_mpc::MotorControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie_mpc::MotorControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyflie_mpc::MotorControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29ed5a63544f3887c01e281980c939e1";
  }

  static const char* value(const ::crazyflie_mpc::MotorControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29ed5a63544f3887ULL;
  static const uint64_t static_value2 = 0xc01e281980c939e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyflie_mpc::MotorControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyflie_mpc/MotorControl";
  }

  static const char* value(const ::crazyflie_mpc::MotorControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyflie_mpc::MotorControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 m1\n\
uint16 m2\n\
uint16 m3\n\
uint16 m4\n\
";
  }

  static const char* value(const ::crazyflie_mpc::MotorControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyflie_mpc::MotorControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m1);
      stream.next(m.m2);
      stream.next(m.m3);
      stream.next(m.m4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyflie_mpc::MotorControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazyflie_mpc::MotorControl_<ContainerAllocator>& v)
  {
    s << indent << "m1: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.m1);
    s << indent << "m2: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.m2);
    s << indent << "m3: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.m3);
    s << indent << "m4: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.m4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYFLIE_MPC_MESSAGE_MOTORCONTROL_H
