(cl:defpackage crazyflie_driver-msg
  (:use )
  (:export
   "<FULLSTATE>"
   "FULLSTATE"
   "<GENERICLOGDATA>"
   "GENERICLOGDATA"
   "<HOVER>"
   "HOVER"
   "<LOGBLOCK>"
   "LOGBLOCK"
   "<MOTORCONTROL>"
   "MOTORCONTROL"
   "<POSITION>"
   "POSITION"
   "<TRAJECTORYPOLYNOMIALPIECE>"
   "TRAJECTORYPOLYNOMIALPIECE"
   "<CRTPPACKET>"
   "CRTPPACKET"
  ))

